---
dist: xenial
language: python
python: "3.10"
os: linux
services:
  - docker
install:
  - pip install -I pipenv
  - pipenv sync
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
  jobs:
    - MOLECULE_DISTRO=debian:bullseye-slim
    - MOLECULE_DISTRO=debian:buster-slim
    - MOLECULE_DISTRO=debian:stretch-slim
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
