---

vector_config_template_path: "testvector.toml.j2"
vector_parser_config:
  - application:
    name: "test"
    path_log: "/var/log/vector"
    parse_vrl: ". = parse_grok!(.message, \"%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}\")\\n.new_field = \"Value in fake field\"\\ndel(.level)\\n.timestamp = to_timestamp!(.timestamp)"
